### ISSUE TITLE
Converter errors out when processing

### ISSUE THREAD

**Issue by DionBlox1** [rojo-rbx/rbxlx-to-rojo#72]
I was converting my game to Rojo until when processing started, it errored out saying: "thread 'main' panicked at 'can't write folder: Os { code: 123, kind: Other, message: "The filename, directory name, or volume label syntax is incorrect." }', src\filesystem.rs:96:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[process exited with code 101 (0x00000065)]"
![Screenshot 2023-10-13 133201](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/90649001/2f83cf8e-c731-44af-89ab-2a85bb9ac078)

--EDIT--
Here is the log: `Starting processing, please wait a bit...`

**Comment by DionBlox1** [comment]
Update: I tried a fresh place file, and it works, but when I use my place, it errors out
![image](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/90649001/fd01b963-8a8a-4edf-8c8a-7b8e1f3e1ac0)

--EDIT--
Tried using PowerShell, still doesn't work
![image](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/90649001/1fabff9c-f4bc-4c64-9ad8-c8e56d26c6a2)

**Comment by kennethloeffler** [comment]
This means you have scripts or ancestors of scripts with names that contain illegal characters. [Windows is unable to create many filenames:](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions)
```
Use any character in the current code page for a name, including Unicode characters and characters in the extended character set (128–255), except for the following:
    The following reserved characters:
        < (less than)
        > (greater than)
        : (colon)
        " (double quote)
        / (forward slash)
        \ (backslash)
        | (vertical bar or pipe)
        ? (question mark)
        * (asterisk)
```

**Comment by DionBlox1** [comment]
Does it only apply to folders/models/decendents?

**Comment by kennethloeffler** [comment]
Because rbxlx-to-rojo only converts scripts, it will apply to scripts or ancestors of scripts that have any of the disallowed characters in their names. It doesn't matter what class the ancestors belong to, they just can't have any illegal characters in their names. 

So for example, this is ok:
![image](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/13822714/de927464-c31c-462d-9a2b-2fc6eb604b21)

But this is not:
![image](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/13822714/96734c44-9a06-4a14-ae03-9df2b5fd1539)

And neither is this:
![image](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/13822714/dffe5760-e74c-4fb0-a47c-e972442ca8d5)

**Comment by DionBlox1** [comment]
I tried to use ' " ' but showed evreuything. I tried chat gpt but did not work. Is there a way to find "?
EDIT: I searched evreything but no results on ilegal characters.

**Comment by DionBlox1** [comment]
Nvm, i found a model which had invalid characters and fixed it. It works.
![Screenshot 2023-10-30 212859](https://github.com/rojo-rbx/rbxlx-to-rojo/assets/90649001/0b79c84d-e05b-40c9-8d06-09d26a538418)
